### ISSUE TITLE
install on vds, error

### ISSUE THREAD

**Issue by glav-hub** [amanibwasp/AudioFromVideoTelegramBot#1]
MoviePy error: the file .\downloaded\video881141390.mp4 could not be found!
Please check that you entered the correct path.

everything is fine on the local computer
A **.\downloaded** folder is created on the VDS,
And **downloaded** on the local computer

**Comment by amanibwasp** [comment]
Thank you for your comment. Maybe the reason is that the format of paths that is used on ur VDS must be different. Try to change it in the code according to how it should be. Please give feedback, was it useful or not.

**Comment by glav-hub** [comment]
thanks for the tip, I specified the full path to the folder in the code

`@dp.message_handler(state=FSM.get_href)
async def get_href(message: types.Message):
    href = message.text
    try:
        video = pytube.YouTube(href)
        videotitle = video.title
        video.streams.filter(res='360p', file_extension='mp4').first().download(r'/usr/local/bin/bot_url_audio_youtube/downloaded',
                                                                                filename=fr'video{message.from_user.id}.mp4')
        audio = moviepy.editor.VideoFileClip(f"/usr/local/bin/bot_url_audio_youtube/downloaded//video{message.from_user.id}.mp4").audio
        audio.write_audiofile(fr'/usr/local/bin/bot_url_audio_youtube/downloaded/audio{message.from_user.id}.mp3')
        await bot.send_audio(message.from_user.id, open(fr'/usr/local/bin/bot_url_audio_youtube/downloaded/audio{message.from_user.id}.mp3', 'rb'),
                             title=videotitle)
        os.remove(fr'/usr/local/bin/bot_url_audio_youtube/downloaded/audio{message.from_user.id}.mp3')
        os.remove(fr'/usr/local/bin/bot_url_audio_youtube/downloaded/video{message.from_user.id}.mp4')
        await bot.send_message(message.from_user.id, done_message)
    except Exception as ex:
        await bot.send_message(message.from_user.id, error_message)
        print(ex)`
